server:
  port: 8081

nivesh:
  auth:
    url: ${AUTH_URL:http://localhost:${server.port}}
    token:
      onboarded-expiry: 10
      access-expiry: 15
      refresh-expiry: 7
    database:
      schema: auth
    cache:
      lock-duration-in-hour: 5
      max-attempts: 3
      max-cache-size: 10000

spring:
  application:
    name: authentication
  config:
    import: optional:configserver:${CONFIG_SERVER:http://localhost:8888}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/nivesh}?currentSchema=${nivesh.auth.database.schema}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: ${nivesh.auth.database.schema}
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    schemas: ${nivesh.auth.database.schema}
    location: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  mail:
    host: smtp.ethereal.email
    port: 587
    username: ${MAIL_ID:bonnie33@ethereal.email}
    password: ${MAIL_PWD:VdEK8XvVHqgYRS9CwG}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  security:
    user:
      name: nivesh
      password: password
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST:localhost}

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.nivesh.library.service.OtpCacheService: TRACE