INSERT INTO products (
    id,
    product_code,
    product_name,
    product_prefix,
    sequence_name,
    min_balance,
    interest_rate,
    max_withdrawal_limit,
    features,
    is_active,
    created_at,
    created_by,
    updated_at,
    updated_by
) VALUES
(
    gen_random_uuid(),
    '001',
    'Savings Account',
    '1',
    'seq_saving',
    1000.00,
    3.50,
    50000.00,
    '{
        "atm_access": true,
        "internet_banking": true,
        "mobile_banking": true,
        "cheque_book": true,
        "debit_card": true,
        "nominee_facility": true,
        "auto_sweep": false
    }'::jsonb,
    true,
    NOW(),
    'SYSTEM',
    NULL,
    NULL
),
(
    gen_random_uuid(),
    '002',
    'Current Account',
    '2',
    'seq_current',
    10000.00,
    0.00,
    500000.00,
    '{
        "atm_access": true,
        "internet_banking": true,
        "mobile_banking": true,
        "cheque_book": true,
        "debit_card": true,
        "overdraft_facility": true,
        "bulk_transactions": true,
        "dedicated_relationship_manager": false
    }'::jsonb,
    true,
    NOW(),
    'SYSTEM',
    NULL,
    NULL
),
(
    gen_random_uuid(),
    '003',
    'Salary Account',
    '3',
    'seq_salary',
    0.00,
    3.50,
    100000.00,
    '{
        "atm_access": true,
        "internet_banking": true,
        "mobile_banking": true,
        "cheque_book": true,
        "debit_card": true,
        "zero_min_balance": true,
        "personal_accident_insurance": true,
        "auto_sweep": true
    }'::jsonb,
    true,
    NOW(),
    'SYSTEM',
    NULL,
    NULL
),
(
    gen_random_uuid(),
    '005',
    'Premium Wealth Account',
    '4',
    'seq_premium',
    100000.00,
    4.25,
    2000000.00,
    '{
        "atm_access": true,
        "internet_banking": true,
        "mobile_banking": true,
        "cheque_book": true,
        "debit_card": true,
        "priority_banking": true,
        "dedicated_relationship_manager": true,
        "lounge_access": true,
        "investment_advisory": true,
        "auto_sweep": true,
        "forex_card": true
    }'::jsonb,
    true,
    NOW(),
    'SYSTEM',
    NULL,
    NULL
);

